# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ben.goodacre.name/tech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Benjamin Goodacre technical blog, which is mostly a historical archive
  rather than being actually useful. - With posts dating from 2007 and few
  posts after 2009.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

#baseurl: "/tech" # the subpath of your site, e.g. /blog
#url: "/" # the base hostname & protocol for your site


twitter_username: benvaljean
github_username:  benvaljean
gitlab_username:  pages

# Outputting
permalink: /tech/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

plugins:
  - jekyll-last-modified-at
  - jekyll-toc
  - jekyll-paginate


paginate: 10
paginate_path: "/tech/page:num/"

last-modified-at:
  date-format: '%d %B %Y %H:%M:%S'

defaults:
  - scope:
      path: ""
    values:
      toc: true
